config/routes.rb
  Rails.application.routes.draw do

  namespace :site do
    get 'home' => 'home#index'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_details, only: [:show]

  end

  namespace :backoffice do
    get '' => 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:destroy, :show]
    resources :admins, except: [:show]
    get 'dashboard' => 'dashboard#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions' }
  root 'site/home#index'

end

app/models/backoffice.rb
module Backoffice
  def self.table_name_prefix
    'backoffice_'
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} registada com sucesso"
    else
      render :new
    end
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} actualizada com sucesso"
    else
      render :edit
    end
  end

  def edit

  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador #{admin_email} Removido com sucesso"
    else
      render :index
    end

  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    pwd = params[:admin][:password]
    pwd_confirm = params[:admin][:password_confirmation]

    if pwd.blank? && pwd_confirm.blank?
      params[:admin].except!(:password, :password_confirmation)
    end

      if @admin.blank?
        params.require(:admin).permit(:name, :role, :email, :password, :password_confirmation)
      else
        params.require(:admin).permit(policy(@admin).permit_attributes)
      end
  end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController

  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} registada com sucesso"
    else
      render :new
    end
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} actualizada com sucesso"
    else
      render :edit
    end
  end

  def edit

  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end
end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController

  def index
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

  def edit
    @admin = Admin.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def create
    AdminMailer.send_message(current_admin, params[:'recipient-name'],params[:'subject-text'],params[:'message-text'])
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin # see pundit doc
  end

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Editando Administrador"}%>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>
<div class="panel panel-default">
  <div class="panel-heading">
    <% if policy(@admins).new? %>
      <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle" do %>
        <i class="fa fa-plus"></i>
      <% end %>
    <% end %>
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
        <tr>
          <th>#</th>
          <th>Email</th>
          <th>Acesso</th>
          <th>Acçoes</th>
        </tr>
        </thead>
        <tbody>
        <% @admins.each do |admin|  %>
          <tr>
            <td> <%= admin.id %> </td>
            <td> <%= admin.name %> </td>
            <td> <%= admin.email %> </td>
            <td> <%= admin.role_desc %> </td>
            <td>
              <%= link_to edit_backoffice_send_mail_path(admin.id), class:"btn btn-info btn-circle", data:{toogle: 'modal', target: '#sendMailModal'}, remote: true do %>
                <i class="fa fa-envelope-o"></i>
              <% end %>
              <%= link_to edit_backoffice_admin_path(admin.id), class:"btn btn-primary btn-circle" do %>
                <i class="fa fa-edit"></i>
              <% end %>
              <% if current_admin.id != admin.id %>
                <%= link_to backoffice_admin_path(admin.id), method: :delete, class:"btn btn-danger btn-circle", data:{confirm:  "Tem acerteza?"} do %>
                  <i class="fa fa-times"></i>
                <% end %>
                <% else %>
                  <%= link_to '#', disabled: "disabled", class:"btn btn-danger btn-circle" do %>
                    <i class="fa fa-times"></i>
                  <% end %>
              <% end %>
            </td>
        <% end %>
        </tbody>
      </table>
    </div>
    <!-- /.table-responsive -->
  </div>
  <!-- /.panel-body -->
</div>


<%= render partial: 'backoffice/admins/shared/send_mail' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Novo Administrador"}%>