config/routes.rb
  Rails.application.routes.draw do

  namespace :site do
    get 'home' => 'home#index'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
    end

    resources :ad_details, only: [:show]

  end

  namespace :backoffice do
    get '' => 'dashboard#index'
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:destroy, :show]
    resources :admins, except: [:show]
    get 'dashboard' => 'dashboard#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { sessions: 'members/sessions' }
  root 'site/home#index'

end

app/models/ad.rb
class Ad < ActiveRecord::Base

  # Callbacks
  before_save :md_to_html

  # Relations
  belongs_to :category
  belongs_to :member

  # validates
  validates :title, :description_md, :description_short, :category, :picture, :finish_date, presence: true
  validates :price, numericality: { :greater_than => 0 }
  # paperclip
  has_attached_file :picture, styles: { large: "900x400#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  # gem money-rails
  monetize :price_cents

  # scope

  scope :descending_order, -> (quantity = 10) {order(created_at: :desc).limit(quantity)}
  scope :of_the, -> (member) {where(member: member)}

  # Functions

  private
  def md_to_html()
    options = {
        filter_html: true,
        link_attributes: {
            rel: "nofollow",
            target: "_blank"
        }
    }

    extensions = {
        space_after_headers: true,
        autolink: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    self.description = markdown.render(self.description_md)
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  ROLES = {:full_access => 0, :restricted_access => 1}

  enum role: ROLES

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :with_restricted_access, -> {where(role: ROLES[:restricted_access])}

  def role_desc
    if self.role == 'full_access'
      'Full Access'
    else
      'Restricted Access'
    end
  end
end

app/models/backoffice.rb
module Backoffice
  def self.table_name_prefix
    'backoffice_'
  end
end

app/models/category.rb
class Category < ActiveRecord::Base

  validates_presence_of :description

  # scope
  scope :order_by_description, -> {order(:description) }

end

app/models/member.rb
class Member < ActiveRecord::Base

  has_many :ads
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Pundit
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Set layout
  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller? && resource_name == :admin
      "backoffice_devise"
    elsif devise_controller? && resource_name == :member
      "site_devise"
    else
      "application"
    end
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]

  def index
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} registada com sucesso"
    else
      render :new
    end
  end

  def update
    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "Administrador #{@admin.email} actualizada com sucesso"
    else
      render :edit
    end
  end

  def edit

  end

  def destroy
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "Administrador #{admin_email} Removido com sucesso"
    else
      render :index
    end

  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    pwd = params[:admin][:password]
    pwd_confirm = params[:admin][:password_confirmation]

    if pwd.blank? && pwd_confirm.blank?
      params[:admin].except!(:password, :password_confirmation)
    end

      if @admin.blank?
        params.require(:admin).permit(:name, :role, :email, :password, :password_confirmation)
      else
        params.require(:admin).permit(policy(@admin).permit_attributes)
      end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin # see pundit doc
  end

end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController
  protected

  def after_sign_in_path_for(_resource)
    site_profile_dashboard_index_path
  end
end

app/controllers/site/ad_details_controller.rb
class Site::AdDetailsController < SiteController

  def show
    @ad = Ad.find(params[:id]);
  end

end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.order_by_description;
    @ads = Ad.descending_order(10);
  end
end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController

  layout "profile"

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  layout "site"


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/site/ad_details_helper.rb
module Site::AdDetailsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administrador</h1>
<% if @admin.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3><%= action %></h3>
  </div>
  <div class="panel-body">
    <%= form_for([:backoffice, @admin]) do |f| %>
      <div class="form-group">
        <label>Name</label>
        <%= f.text_field :name, class: "form-control", placeholder: "Enter Name"%>
      </div>
      <div class="form-group">
        <label>Email</label>
        <%= f.text_field :email, class: "form-control", placeholder: "Enter Email"%>
      </div>
      <% if policy(@admin).edit? %>
        <div class="form-group">
          <%= f.label :role %>
          <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
            <div class="radio">
              <%= b.label { b.radio_button + b.text} %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <label>Password</label>
        <%= f.password_field :password, class: "form-control", placeholder: "Enter Password"%>
      </div>
      <div class="form-group">
        <label>Password Confirmation</label>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter Password Confirmation"%>
      </div>
      <button type="submit" class="btn btn-default">Submit Button</button>
      <button type="reset" class="btn btn-default">Reset Button</button>
    <% end %>
  </div>
  <!-- /.panel-body -->
</div>

app/views/backoffice/admins/shared/_send_mail.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path , remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" disabled="disabled" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="subject-name" class="control-label">Subject:</label>
            <input type="text" class="form-control" id="subject-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Send message", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/shared/_notification.html.erb
<% if notice %>
    <%= javascript_tag "$.notify( { message: '#{notice}'},
                                  { type: 'success',
                                    placement: {  from: 'top',
                                                  align : 'center'}});" %>
<% end %>

 <% if alert %>
  <%= javascript_tag
      "$.notify({
        // options
        message: '#{alert}'
      },{
        // settings
        type: 'danger',
        placement: {
          from: 'top',
          align: 'center'
        }
      });"
  %>
 <% end %>